spring: 
  profiles:  
    active: 
    - dev
---
spring: 
  profiles: dev
  application: 
    name: servicecloud-config-share-dev
---
spring: 
  profiles: test
      application: 
        name: servicecloud-config-share-test